Add metadados para social network
rede-cidada/rede-cidada-no-hacktoberfest2020 pull request #4
Opened 2020-10-02 13:54 UTC by alinecbsr

Add metadados para social network

2020-10-06 21:21 UTC, simoneas02 requested changes
Vê só os doi comentários aheee e sobe novamente q aprovo aq, bjuss

2020-10-06 21:21 UTC, simoneas02 commented on public/index.html
> -      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap"
aqui tu deixa a linha antiga mesmo, pq não vou sar a mesma fonte do WWCode.

```<link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap" />```

2020-10-06 21:21 UTC, simoneas02 commented on public/index.html
> +    <meta name="twitter:creator" content="@RedeCidada" />
Aqui dá pra remover o ```witter:site``` e ```twitter:creator``` pq não temos page no twitter

2020-10-07 12:22 UTC, alinecbsr commented
Required adjustments

2020-10-07 13:31 UTC, merged